apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbuild-gke-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudbuild-gke
  template:
    metadata:
      labels:
        app: cloudbuild-gke
    spec:
      containers:
      - name: cloudbuild-gke
        image: 'us-central1-docker.pkg.dev/$PROJECT_ID/helloworld-docker-repo/cloudbuild_gke:tag1'
        ports:
        - containerPort: 80 
